source $HOME/.local/share/zsh/environment.zsh
source $HOME/.local/share/zsh/functions.zsh
source $HOME/.local/share/zsh/aliases.zsh

setopt extendedglob nomatch

# Disable beep on syntax error
unsetopt autocd beep notify

# Vi key bindings
bindkey -v

zstyle :compinstall filename '/home/khaos/.zshrc'

autoload -Uz compinit
compinit

# Load plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
