
source $HOME/.local/share/zsh/environment.zsh
source $HOME/.local/share/zsh/aliases.zsh
source $HOME/.local/share/zsh/functions.zsh
source $HOME/.local/share/zsh/=DISTRO=_helpers.zsh

# Set options
setopt extendedglob nocaseglob nomatch numericglobsort appendhistory

# Unset options
unsetopt autocd beep notify

# Vi key bindings
bindkey -v

# Autocompletion
autoload -Uz compinit colors
compinit