#!/bin/bash

source dotfiles/zsh/environment.zsh
source dotfiles/zsh/functions.zsh

# Count input arguments
if [[ "$#" -lt '2' ]]; then
	error "Additional arguments are required! \nUsage: ./build-setup <github username> <your email> (or vice-versa)"
else
	for arg in ${@}; do
		if [[ ${arg} =~ '@' ]]; then
			GIT_USER_MAIL=${arg}
		else
			GIT_USER_NAME=${arg}
		fi
	done
	if [[ -z ${GIT_USER_NAME} ]] || [[ -z ${GIT_USER_MAIL} ]]; then
		error "Improper arguments, either git email or username is missing"
	fi
fi

# Setup directory structure
mkdir -p ${ENV_MISC} \

# Check whether we are running either Debian or Arch based distro
if [[ $(lsb_release -i -s | tr '[:upper:]' '[:lower:]') != 'arch' ]]; then
	error "I exclusively use Arch, go away!"
fi

# Arch4Life
dependencies=(
	android-tools
	android-udev
	base-devel
	bc
	ccache
	clang
	curl
	gcc
	gnupg
	gperf
	imagemagick
	lib32-ncurses
	lib32-readline
	lib32-zlib
	libxslt
	lzop
	multilib-devel
	ncurses
	perl-switch
	pngcrush
	reflector
	repo
	rsync
	schedtool
	sdl
	squashfs-tools
	ttf-dejavu
	unzip
	wxgtk2
	xclip
	zip
	zlib
	zsh
	zsh-completions
	zsh-syntax-highlighting
)

# Configure multilib, makepkg and update before installing our tools
warning "Configuring multilib"
sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
sudo sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$(nproc --all)\"/g" /etc/makepkg.conf
sudo pacman -Syyu --noconfirm || error "Something went wrong while updating packages"

# Install required dependencies
warning "Installing required dependencies"
sudo pacman -S --needed --noconfirm ${dependencies[@]} || error "Error installing dependencies"

# Install AUR dependencies if on Arch
warning "Installing required dependencies from AUR"
gpg --keyserver keys.gnupg.net --recv-keys 702353E0F7E48EDB # This will import missing PGP key
yay -S --answerclean A --answerdiff N --needed \
	lib32-ncurses5-compat-libs \
	ncurses5-compat-libs \
	xml2 || error "Error installing required dependencies from AUR"

# Cleanup
warning "Cleaning up"
sudo pacman -Sc --noconfirm
pacman -Qtdq | sudo pacman -Rns --noconfirm - 2> /dev/null

# Oh My ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
sed -i 's/robbyrussell/agnoster/' $HOME/.zshrc

function restore_dotfiles() {
	warning "Restoring .${1}"
	cat dotfiles/${1} >> ~/.${1}
}

# Restore core configs
restore_dotfiles zshrc
restore_dotfiles vimrc

cp -r dotfiles/zsh/ $ZSH_CONFIG

# Setup Git
git config --global user.name ${GIT_USER_NAME}
git config --global user.email ${GIT_USER_MAIL}
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
git config --global core.excludesfile ~/.gitignore_global
git config --global core.editor vim

# Add my rules
{
	echo "out/"
	echo "*.ko"
	echo "Image.*"
	echo "zImage*"
	echo "dtbo*"
	echo "net/wireguard"
	echo "*.rej"
	echo ".DS_Store"
	echo ".DS_Store?"
	echo "*.log"
} >> ~/.gitignore_global

# Generate SSH keys
if [[ -f ~/.ssh/id_rsa.pub ]]; then
	warning "Copying your existing SSH key..."
	xclip -sel clip < ~/.ssh/id_rsa.pub
else
	warning "Generating a new SSH key"
	ssh-keygen -t rsa -b 4096 -C "${GIT_USER_MAIL}" -P "" -f ~/.ssh/id_rsa -q
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/id_rsa
	xclip -sel clip < ~/.ssh/id_rsa.pub
fi

warning "Now go to your GitHub account and follow these steps: \n1) Settings \n2) SSH and GPG keys \n3) New SSH key \n4) Click on the 'Key' field and press CTRL+V \n5) Click on 'Add SSH key'"
