#!/bin/zsh

# Print the error message, then exit
function error() {
	echo ""
	echo -e "$fg[red]- error: ${@}$reset_color"
	echo ""
	exit 1
}

# Print the warning message and continue
function warning() {
	echo ""
	echo -e "$fg[green]- warning: ${@}$reset_color"
	echo ""
}

# Enforces the value needed for two-part flags
function enforce_value() {
	if [[ ${#} -lt 1 ]]; then
		error "An additional value is needed for '${@}' flag!"
	fi
}

# Clone Clang or GCC or both if they're not cloned yet
function check_gcc() {
	if [[ ! -d ${PREBUILT_GCC} ]]; then
		warning "The GCC compiler isn't cloned yet! Cloning now..."
		git -C ${ROOT_PATH} clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ ${PREBUILT_GCC}
	fi
}

function check_clang() {
	if [[ ! -d ${PREBUILT_CLANG} ]]; then
		warning "The Clang compiler isn't cloned yet! Cloning now..."
		git -C ${ENV_ANDROID} clone --single-branch https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/ ${PREBUILT_CLANG} || "Git clone failed!"
	else
		warning "Updating repository to its remote HEAD state"
		git -C ${PREBUILT_CLANG} fetch origin master || error "Failed to fetch commits from origin!"
		git -C ${PREBUILT_CLANG} reset --hard origin/master
	fi

	# Get the latest version (we only care about those starting with 'clang-r')
	srcpath=$(pwd)
	cd ${PREBUILT_CLANG}
	clangvers=($(ls -d clang-r* | sort -rn))
	PREBUILT_CLANG_REVISION=${clangvers[0]}
	cd ${srcpath}
}

function ftp_upload_check() {
	if [[ ${FTP_UPLOAD} == 'y' ]] && [[ -f ${ENV_ANDROID}/ftp-afh ]]; then
		source ${ENV_ANDROID}/ftp-afh
	else
		FTP_UPLOAD=n
	fi
}

function abort() {
	rm -rf out
	error "Process terminated by user!"
}

# Initialize sources
AK3_SOURCE=${ENV_ANDROID}/AnyKernel3
TWRP_SOURCE=${ENV_ANDROID}/TWRP

# Initialize prebuilts
PREBUILT_GCC=${ENV_ANDROID}/prebuilt-gcc
PREBUILT_CLANG=${ENV_ANDROID}/prebuilt-clang

# That's me
ME=(
	"khaos@zeniac",
	"khaos@zenpad",
	"khaos@shintel"
)

# Handle terminating the process by pressing CTRL+C with a function
trap abort INT

mkdir -p $ENV_MISC 2>/dev/null
