#!/bin/bash

source ${SCRIPTS}/common

OS_BASE_DIST=$(cat /etc/*release | grep 'ID_LIKE=' | cut -f2 -d "=" | tr '[:upper:]' '[:lower:]')
if [[ -z ${OS_BASE_DIST} ]]; then
	OS_BASE_DIST=$(cat /etc/*release | grep -m 1 'ID=' | cut -f2 -d "=" | tr '[:upper:]' '[:lower:]')
fi

function md() {
	mkdir ${1} && cd ${1}
}

# YAY FTW!
function cleanup() {
	if [[ 'arch' == ${OS_BASE_DIST} ]]; then
		yay -Sc --noconfirm
	else
		sudo apt autoremove -y
	fi
}

function install() {
	if [[ 'arch' == ${OS_BASE_DIST} ]]; then
		yay -S --noconfirm ${@}
	else
		sudo apt install -y ${@}
	fi
}

function nuke() {
	if [[ 'arch' == ${OS_BASE_DIST} ]]; then
		yay -R --noconfirm ${@}
	else
		sudo apt remove -y ${@}
	fi
}

function upgrade() {
	if [[ 'arch' == ${OS_BASE_DIST} ]]; then
		yay -Syyu --noconfirm --nodiffmenu
	else
		sudo apt update && sudo apt upgrade -y
	fi
}

# AOSP stuff
function find-blobs() {
	find ${OOS_MNT}/vendor -name ${*} | awk -F "OOS" '{print $2}' | tee -a '${ANDROID}/proprietary.txt'
}

# Extract it!
function extract () {
	if [[ -f $1 ]]; then
		case $1 in
			*.tar.bz2)
				tar xjf $1
				;;
			*.tar.gz)
				tar xzf $1
				;;
			*.bz2)
				bunzip2 $1
				;;
			*.rar)
				rar x $1
				;;
			*.gz)
				gunzip $1
				;;
			*.tar|*.tar.xz)
				tar xf $1
				;;
			*.tbz2)
				tar xjf $1
				;;
			*.tgz)
				tar xzf $1
				;;
			*.zip)
				unzip $1
				;;
			*.Z)
				uncompress $1
				;;
			*)
				echo "'$1' cannot be extracted via extract()"
				;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}

# Git functions
function gc() {
	gcmsg=${*}
	if [[ -z ${gcmsg} ]]; then
		gcmsg="$(basename $(pwd)): Update"
	fi

	git commit -s -m "${gcmsg}"
}

function ga() {
    git add ${*}
}

function gac() {
	git add . && gc "${*}"
}

function greset() {
	git reset --hard origin/HEAD
}

# Housekeeping
function sync-rc() {
	warning "Syncing scripts and configs..."
	if [[ -d ${SCRIPTS} ]]; then 
		\cp -urf ~/.shell/* ${SCRIPTS}/dotfiles/shell/
		git -C ${SCRIPTS} add .
		git -C ${SCRIPTS} commit -s -m "scripts: Sync config as of $(date +%Y%m%d%H%M)"
		git -C ${SCRIPTS} push origin master
	else
		git clone https://github.com/hejsekvojtech/scripts.git -b master ${SCRIPTS}
		sync-rc
	fi
}
